# Generated by Django 5.1.5 on 2025-02-04 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='available_slot',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(440)]),
        ),
    ]
