# Generated by Django 5.1.5 on 2025-02-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_travel_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='travel_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
