# Generated by Django 5.1.5 on 2025-02-04 23:26

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_travelpackage_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='travel_date',
            field=models.DateField(validators=[bookings.models.validate_travel_date]),
        ),
    ]
