# Generated by Django 5.1.5 on 2025-02-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_travelpackage_travel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONSchema',
            fields=[
                ('name', models.CharField(choices=[('Hotel Details Schema', 'Hotel Details Schema')], max_length=50)),
                ('version', models.AutoField(primary_key=True, serialize=False)),
                ('schema', models.JSONField(default={})),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_details_schema_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel_details',
            field=models.JSONField(default={}),
        ),
    ]
