# Generated by Django 5.1.5 on 2025-02-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_jsonschema_booking_hotel_details_schema_version_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jsonschema',
            unique_together={('version', 'name')},
        ),
    ]
